export type ViewMode = "stacked" | "side-by-side" | "overlay"
export type ViewAngle = "side" | "top" | "front"
export type OverlayAlignment = "nose" | "center" | "tail"
export type StackAlignment = "left" | "center" | "right"
export type UnitSystem = "metric" | "imperial"
